config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :tasks
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member 
      put 'add_user', on: :member 
    end
  end
  
  resources :categories, except: [:destroy]
  
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :task_categories
  has_many :tasks, through: :task_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #タスクに対してカテゴリを付与する機能
  #カテゴリの管理画面には管理者のみがアクセスできる
  
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
    @category.project_id = params[:project_id]
  end
  
  def show
    @category = Category.find(params[:id])
    @category_tasks = @category.tasks.paginate(page: params[:page], per_page: 5)
  end
  
  def create
      @category = Category.new(category_params)
    
      if @category.save
        flash[:success] = "カテゴリを作成しました"
        redirect_to categories_path
      else
        render 'new'
      end
  end
  
  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "カテゴリ名を更新しました"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  private

    def category_params
      params.require(:category).permit(:name, :project_id)
    end
    
    def require_admin
      if !logged_in? || (logged_in? and !current_user.is_admin?)
        flash[:danger] = "管理者のみがアクセスできます"
        redirect_to categories_path
      end
    end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "category name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to tasks listing", tasks_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">カテゴリ名を編集</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<div align="center">
  <%= will_paginate%>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
        <li class="article-title">
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
        <li><small><%= pluralize(category.tasks.count, "task") %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <%= will_paginate%>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<div align="center">
  <% if logged_in? and current_user.is_admin? %>
    <div class="row">
      <span class="badge"><%= link_to "カテゴリ名を編集", edit_category_path(@category) %></span>
    </div>
  <% end %>
  <%= will_paginate @category_tasks %>
</div>

<div align="center">
  <%= will_paginate @category_tasks %>
</div>